const BUILTIN_CATEGORIES = {
  filmes: { label: "Filmes & Séries", icon: "🎬", words: [ "O Senhor dos Anéis","Harry Potter e a Pedra Filosofal","Harry Potter e o Prisioneiro de Azkaban", "Piratas das Caraíbas","Velozes e Furiosos","Missão Impossível","Transformers","Terminator", "Alien","Predador","O Exorcista","It","Scream","Halloween","Saw","The Conjuring", "Annabelle","Insidious","A Freira","Pânico","Coraline","Beetlejuice","Edward Mãos de Tesoura", "Charlie e a Fábrica de Chocolate","Alice no País das Maravilhas","Peter Pan","Aladdin", "Hércules","Moana","Encanto","Ratatouille","Up","Wall-E","Monstros e Companhia", "Procurando Nemo","Os Incríveis","Carros","Madagáscar","Kung Fu Panda","Como Treinares o Teu Dragão", "Minions","Gru","Hotel Transylvania","Ice Age","Rio","Shrek 2","Shrek 3", "The Hangover","Superbad","Ted","American Pie","Scary Movie","Ace Ventura","The Mask", "Dumb and Dumber","Home Alone","The Truman Show","Forrest Gump","O Náufrago", "À Procura da Felicidade","The Wolf of Wall Street","Oppenheimer","Dunkirk","Tenet", "Memento","The Prestige","Parasite","Joker","The Batman","Logan","Venom","Thor", "Iron Man","Hulk","Capitão América","Black Panther","Guardians of the Galaxy", "Doctor Strange","Ant-Man","Aquaman","Wonder Woman","Justice League","Watchmen", "Deadpool 2","X-Men","Wolverine","Godzilla","King Kong","Pacific Rim","Avatar 2", "Dune","Dune 2","Mad Max","Blade Runner","Blade Runner 2049","Ready Player One", "The Hunger Games","Divergente","Maze Runner","Twilight","The Walking Dead", "Lost","Prison Break","Dexter","Better Call Saul","Narcos","Money Heist", "The Mandalorian","Andor","Loki","Daredevil","The Punisher","The Witcher", "Vikings","Spartacus","Suits","House","Sherlock","Black Mirror","The Umbrella Academy", "Cobra Kai","Chernobyl","Mr. Robot","The Boys","Gen V","Euphoria","The Bear", "You","Lucifer","Manifest","Outer Banks","Elite","How I Met Your Mother", "Modern Family","Brooklyn Nine-Nine","Rick and Morty","South Park","Family Guy", "Futurama","Arcane","Invincible","Attack on Titan","Demon Slayer","Jujutsu Kaisen", "My Hero Academia","Death Note","Bleach","Hunter x Hunter","One Punch Man" ]},
  futebol: { label: "Futebol", icon: "⚽", words: [ "Iker Casillas","Gianluigi Buffon","Manuel Neuer","Thibaut Courtois","Alisson", "Ederson","Marc-André ter Stegen","Sergio Ramos","Gerard Piqué","Carles Puyol", "Dani Alves","Marcelo","Roberto Carlos","Cafu","Thiago Silva","Virgil van Dijk", "Rúben Dias","William Saliba","Raphaël Varane","John Stones","Andrew Robertson", "Trent Alexander-Arnold","Achraf Hakimi","Theo Hernández","João Cancelo", "Nuno Mendes","Pepe","Ricardo Carvalho","Fernando Hierro","Franz Beckenbauer", "Johan Cruyff","Michel Platini","George Best","Bobby Charlton","Gerd Müller", "Rivaldo","Kaká","Ronaldo","Romário","Adriano","Kane","Harry Kane","Son Heung-min", "Sadio Mané","Luis Suárez","Karim Benzema","Robert Lewandowski","Antoine Griezmann", "Ousmane Dembélé","Rodrygo","Endrick","Lamine Yamal","Pedri","Gavi","Frenkie de Jong", "Toni Kroos","Sergio Busquets","Casemiro","Rodri","Declan Rice","Martin Ødegaard", "Bernardo Silva","Rúben Neves","Vitinha","João Palhinha","Diogo Jota","Pedro Neto", "Diogo Costa","Rui Patrício","Ricardo Quaresma","Nani","Simão Sabrosa","Deco", "Luís Figo","Eusébio","Vítor Baía","Jorge Costa","Ricardo Carvalho","João Moutinho", "William Carvalho","Raphael Guerreiro","Fábio Coentrão","Éder","Mário Coluna", "José Mourinho","Pep Guardiola","Jürgen Klopp","Carlo Ancelotti","Zinedine Zidane", "Diego Simeone","Sir Alex Ferguson","Arsène Wenger","Carlo Ancelotti", "Manchester City","Tottenham","Newcastle","Aston Villa","West Ham","Everton", "AC Milan","Inter de Milão","Juventus","Napoli","Roma","Lazio","Borussia Dortmund", "Bayer Leverkusen","RB Leipzig","Atlético de Madrid","Sevilla","Valencia", "Athletic Bilbao","Ajax","PSV","Feyenoord","Galatasaray","Fenerbahçe", "Al Nassr","Al Hilal","Flamengo","Palmeiras","Santos","Corinthians","River Plate", "Boca Juniors","Inter Miami","LA Galaxy","Maracanã","Santiago Bernabéu", "San Siro","Signal Iduna Park","Allianz Arena","Emirates Stadium","Etihad Stadium", "Wembley","Parque dos Príncipes","Estádio do Dragão","José Alvalade", "Supertaça","Liga dos Campeões","Liga Europa","Liga Conferência","Liga Portugal", "Premier League","La Liga","Serie A","Bundesliga","Ligue 1","Copa América", "Mundial de Clubes","Taça de Portugal","Taça da Liga","Penalty","Livre direto", "Canto","Fora de jogo","Cartão vermelho","Cartão amarelo","VAR","Hat-trick", "Golo olímpico","Autogolo","Penálti","Prolongamento","Bola de Ouro","Chuteira de Ouro" ]},
  celebridades: { label: "Celebridades", icon: "🌟", words: [ "Kanye West","Kim Kardashian","Kylie Jenner","Kendall Jenner","Khloé Kardashian", "Kourtney Kardashian","Travis Scott","Nicki Minaj","Cardi B","Megan Thee Stallion", "Doja Cat","SZA","Olivia Rodrigo","Sabrina Carpenter","Chappell Roan","Adele", "Katy Perry","Miley Cyrus","Selena Gomez","Demi Lovato","Camila Cabello", "Shawn Mendes","Harry Styles","Zayn Malik","The Weeknd","A$AP Rocky","Travis Scott", "Tyler, The Creator","J. Cole","Eminem","50 Cent","Jay-Z","Snoop Dogg", "Ice Spice","Central Cee","Stormzy","Bad Bunny","J Balvin","Karol G","Shakira", "Jennifer Lopez","Ricky Martin","Daddy Yankee","Justin Timberlake","Usher", "Chris Brown","Jason Derulo","Pitbull","Avicii","David Guetta","Martin Garrix", "Calvin Harris","Tiesto","Skrillex","Steve Aoki","The Rock","Jason Statham", "Arnold Schwarzenegger","Sylvester Stallone","Bruce Willis","Jim Carrey","Adam Sandler", "Jack Black","Chris Hemsworth","Chris Evans","Robert Downey Jr.","Mark Ruffalo", "Jeremy Renner","Scarlett Johansson","Natalie Portman","Anne Hathaway","Gal Gadot", "Margot Robbie","Ryan Gosling","Ryan Reynolds","Hugh Jackman","Tom Cruise", "Bradley Cooper","Johnny Depp","Joaquin Phoenix","Christian Bale","Matt Damon", "Ben Affleck","George Clooney","Morgan Freeman","Samuel L. Jackson","Denzel Washington", "Robert De Niro","Al Pacino","Jack Nicholson","Jim Carrey","Rowan Atkinson", "Steve Carell","Jim Parsons","Matthew Perry","Jennifer Aniston","Courteney Cox", "Lisa Kudrow","Matt LeBlanc","David Schwimmer","Kit Harington","Emilia Clarke", "Sophie Turner","Maisie Williams","Pedro Pascal","Oscar Isaac","Jenna Ortega", "Millie Bobby Brown","Finn Wolfhard","Gaten Matarazzo","Sadie Sink","Jacob Elordi", "Sydney Sweeney","Anya Taylor-Joy","Timothée Chalamet","Austin Butler", "Florence Pugh","Cillian Murphy","Paul Mescal","Barry Keoghan","Jeremy Allen White", "MrBeast","Kai Cenat","IShowSpeed","PewDiePie","KSI","Logan Paul","Jake Paul", "Ninja","Pokimane","xQc","Ibai","AuronPlay","El Rubius","Cristiano Ronaldo", "Lionel Messi","Neymar","Kylian Mbappé","Lewis Hamilton","Max Verstappen", "Charles Leclerc","Lando Norris","Fernando Alonso","Conor McGregor","Mike Tyson", "Muhammad Ali","Michael Phelps","Usain Bolt","Shaquille O'Neal","Stephen Curry", "Kobe Bryant","Tiger Woods","Tom Brady","Serena Williams","Roger Federer" ]},
  animais: { label: "Animais", icon: "🐾", words: [ "Leopardo","Chita","Onça","Pantera","Hiena","Coiote","Chacal","Texugo","Doninha", "Lontra","Castor","Preguiça","Tamanduá","Tatu","Ouriço","Morcego","Esquilo voador", "Suricata","Babuíno","Orangotango","Gibão","Lémure","Macaco-aranha","Mico", "Hipopótamo","Rinoceronte","Girafa","Búfalo","Bisão","Alce","Veado","Rena", "Camelo","Dromedário","Lhama","Alpaca","Burro","Mula","Javali","Porco-espinho", "Doninha","Furão","Panda gigante","Urso-pardo","Urso-negro","Raposa-do-ártico", "Canguru","Wallaby","Diabo-da-Tasmânia","Ornitorrinco","Equidna","Foca-leopardo", "Morsa","Narval","Orca","Beluga","Cachalote","Lula-gigante","Lula","Medusa", "Estrela-do-mar","Cavalo-marinho","Peixe-palhaço","Piranha","Enguia","Raia", "Peixe-espada","Atum","Salmão","Truta","Caranguejo","Lagosta","Camarão", "Lagostim","Mexilhão","Ostra","Caracol","Lesma","Aranha","Tarântula","Escorpião", "Louva-a-deus","Barata","Formiga","Abelha","Vespa","Mosquito","Mosca","Libélula", "Borboleta","Mariposa","Besouro","Joaninha","Gafanhoto","Grilo","Cigarra", "Minhoca","Sanguessuga","Salamandra","Axolote","Sapo","Rã","Salamandra-gigante", "Camaleão","Lagarto","Gecko","Dragão-de-Komodo","Jiboia","Píton","Naja", "Cascavel","Víbora","Tartaruga-marinha","Tartaruga-gigante","Iguana-marinha", "Crocodilo-do-Nilo","Jacaré","Aligátor","Komodo","Águia-real","Águia-careca", "Abutre","Condor","Andorinha","Gaivota","Flamingo","Cegonha","Garça","Pelicano", "Pavão","Avestruz","Emu","Casuar","Kiwi","Pato","Ganso","Cisne","Peru", "Galinha","Galo","Pombo","Corvo","Gralha","Pica-pau","Martim-pescador", "Tucano","Arara","Canário","Periquito","Papagaio-cinzento","Cacatua","Coruja-das-neves" ]},
  objetos: { label: "Objetos", icon: "🧰", words: [ "Mesa de cabeceira","Estante","Armário","Roupeiro","Cómoda","Banco","Banqueta", "Secretária","Gaveta","Prateleira","Porta","Janela","Cortina","Tapete","Vaso", "Relógio despertador","Calendário","Caderno","Agenda","Borracha","Afia","Régua", "Marcador","Caneta permanente","Estojo","Calculadora","Agrafador","Agrafos", "Clips","Post-it","Envelope","Carta","Selo","Carimbo","Impressora","Scanner", "Rato","Teclado","Monitor","Webcam","Colunas","Auscultadores","Headset","Pen USB", "Disco externo","Router","Cabo HDMI","Carregador","Powerbank","Tomada","Extensão", "Adaptador","Comando da televisão","Comando da consola","Consola","PlayStation", "Xbox","Nintendo Switch","Comando universal","Lanterna","Vela","Isqueiro","Fósforos", "Canivete","Alicate","Serrote","Berbequim","Parafuso","Prego","Porca","Anilha", "Fita-cola","Cola quente","Super cola","Tesoura de poda","Escadote","Caixa de ferramentas", "Fita métrica","Nível","Chave inglesa","Chave Allen","Chave Phillips","Martelo", "Vassoura","Esfregona","Balde","Pá","Escova","Esponja","Detergente","Sabão", "Toalha","Papel higiénico","Guardanapo","Rolo de cozinha","Escova de dentes", "Pasta de dentes","Champô","Gel de banho","Perfume","Desodorizante","Pente", "Secador","Máquina de barbear","Barbeador","Espelho de mão","Pinça","Tesoura de unhas", "Mala de viagem","Mala de mão","Carteira","Porta-moedas","Passaporte","Bilhete", "Chapéu","Boné","Cachecol","Luvas","Cinto","Gravata","Meias","Botas","Chinelos", "Ténis","Casaco","Sweatshirt","Camisola","Calças","Calções","T-shirt","Camisa", "Fato","Pijama","Óculos","Óculos de natação","Máscara","Capacete","Colete", "Guarda-sol","Tenda","Saco-cama","Colchão insuflável","Bússola","GPS","Mapa", "Binóculos","Máquina fotográfica","Tripé","Drone","Microfone","Coluna Bluetooth", "Guitarra","Piano","Bateria","Violino","Ukulele","Raquete","Bola","Skate", "Bicicleta","Capacete de bicicleta","Mochila","Prancha de surf","Barco","Caiaque" ]},
  aleatorias: { label: "Palavras Aleatórias", icon: "🔀", words: [
    "Avião","Comboio","Metro","Autocarro","Táxi","Ambulância","Helicóptero","Navio", "Submarino","Foguetão","Satélite","OVNI","Alienígena","Robô","Ciborgue","Dinossauro", "Vulcão","Terramoto","Tsunami","Tornado","Furacão","Arco-íris","Eclipse","Lua cheia", "Estrela cadente","Buraco negro","Planeta","Astronauta","Espaço","Marte","Lua", "Deserto","Selva","Montanha","Glaciar","Caverna","Ilha deserta","Praia","Cachoeira", "Rio","Lago","Oceano","Farol","Ponte","Túnel","Arranha-céus","Castelo","Palácio", "Pirâmide","Templo","Igreja","Museu","Biblioteca","Escola","Universidade","Hospital", "Prisão","Banco","Casino","Hotel","Aeroporto","Estação","Supermercado","Shopping", "Restaurante","Discoteca","Bar","Festival","Concerto","Estádio","Parque de diversões", "Montanha-russa","Roda gigante","Carrossel","Circo","Palhaço","Mágico","Ilusionista", "Pirata","Ninja","Samurai","Viking","Cavaleiro","Gladiador","Rei","Rainha","Imperador", "Princesa","Dragão","Unicórnio","Sereia","Vampiro","Lobisomem","Múmia","Fantasma", "Zumbi","Bruxa","Feiticeiro","Monstro","Super-herói","Supervilão","Detetive", "Espião","Assassino","Ladrão","Fugitivo","Polícia","Bombeiro","Médico","Cientista", "Professor","Astronauta","Chef","Cantor","Ator","Influencer","Hacker","Milionário", "Bilionário","Presidente","Celebridade","Jogador de futebol","Rockstar","DJ", "Casamento","Divórcio","Aniversário","Funeral","Férias","Viagem","Lua de mel", "Primeiro encontro","Festa surpresa","Reunião","Entrevista","Exame","Aula", "Acidente","Perseguição","Fuga","Assalto","Mistério","Segredo","Tesouro","Mapa", "Cofre","Código secreto","Chave","Coroa","Anel","Medalha","Trofeu","Diamante", "Ouro","Dinheiro","Bilhete premiado","Loteria","Jackpot","Aposta","Roleta","Poker", "Dados","Baralho","Máscara","Fantoche","Boneca","Brinquedo","Peluches","Balão", "Pipa","Bumerangue","Íman","Ampulheta","Bússola","Binóculos","Lanterna","Câmara", "Microfone","Megafone","Walkie-talkie","Telefone público","Cabine telefónica", "Máquina de escrever","Máquina de arcade","Máquina do tempo","Portal","Teletransporte", "Multiverso","Universo paralelo","Realidade virtual","Simulação","Apocalipse", "Fim do mundo","Invasão alienígena","Viagem no tempo","Experiência científica", "Laboratório secreto","Base militar","Bunker","Área 51","Triângulo das Bermudas", "Cidade abandonada","Casa assombrada","Hotel abandonado","Floresta escura", "Ilha misteriosa","Navio fantasma","Tesouro perdido","Civilização perdida" ]},
  portoDeMos: { label: "Pessoas de Porto de Mós e Arredores",icon: "📍",words: [
 "Fast",
    "Maria Vazão",
    "Daniela Silva",
    "Liane Serraria",
    "Serranos",
    "Marco",
    "Pato",
    "RubÉEn",
    "Pinhoca",
    "Gonça esplanada",
    "Cunhado Jesus",
    "Mário Vieira",
    "Piuga",
    "Marcão",
    "Toninho",
  ]},

grupo: {
  label: "Pessoas do Grupo",
  icon: "🍻",
  words: [
    "Anastácio",
    "Rosa",
    "Peça",
    "Beato",
    "Deco",
    "Pimenta",
    "Durão",
    "Afonso",
    "Mitchel",
    "Jesus",
    "Faf",
    "Campos",
    "Nunes"
  ]},
  aleatoriasssss: {
    label: "Mais aleatorias +",
    icon: "xdddx",
    words:[ "Pé de cabra", "Chulé", "Cueca", "Tampão", "Bidão", "Bidé", "Pinguim", "Beringela", "Pneu", "Bigode", "Careca", "Cromossoma", "Salsicha", "Presunto", "Chouriço", "Alheira", "Morcela", "Bacalhau", "Sardinha", "Carapau", "Pombo", "Gaivota", "Rato", "Barata", "Mosquito", "Percevejo", "Lesma", "Caracol", "Sapo", "Girafa", "Hipopótamo", "Ornitorrinco", "Macaco", "Gorila", "Crocodilo", "Dinossauro", "Cacto", "Batata", "Cebola", "Alho", "Pepino", "Milho", "Nabo", "Abóbora", "Melancia", "Banana", "Mandioca", "Pipoca", "Bolacha", "Croissant", "Pastel de nata", "Bolo de arroz", "Pudim", "Gelatina", "Maionese", "Ketchup", "Mostarda", "Molho de alho", "Colher", "Garfo", "Concha", "Tupperware", "Vassoura", "Esfregona", "Aspirador", "Estendal", "Pregador", "Desentupidor", "Rolo de papel higiénico", "Papel higiénico", "Caixote do lixo", "Saco do lixo", "Extintor", "Cone de trânsito", "Semáforo", "Buzina", "Matrícula", "Retrovisor", "Porta-luvas", "Macaco hidráulico", "Pneu sobressalente", "Chinelo", "Pantufa", "Meia", "Crocs", "Sandália", "Gravata", "Fato de treino", "Óculos de natação", "Touca", "Guarda-chuva", "Mochila", "Fivela", "Fecho éclair", "Velcro", "Bigode postiço", "Peruca", "Dentadura", "Prótese", "Muleta", "Caneca", "Bidão de água", "Termo", "Garrafão", "Funil", "Balde", "Bacia", "Esponja", "Pano", "Papelão", "Fita cola", "Agrafador", "Calculadora", "Pen USB", "Comando", "Rato do computador", "Teclado", "Impressora", "Router", "Cabo HDMI", "Carregador", "Powerbank", "Selfie stick", "Tripé", "Karaoke", "Microfone", "Megafone", "Buzina de ar", "Apito", "Corneta", "Confettis", "Purpurinas", "Balão", "Piñata", "Disfarce", "Mascote", "Palhaço", "Mimo", "Bobo da corte", "Tarzan", "Ninja", "Pirata", "Cowboy", "Viking", "Cavaleiro", "Feiticeiro", "Duende", "Gnomo", "Sereia", "Unicórnio", "Yeti", "ET", "Alien", "Robô", "Zombi", "Vampiro", "Múmia", "Fantasma", "Monstro", "Mãozinha", "Nariz", "Orelha", "Sobrancelha", "Unha", "Pestana", "Umbigo", "Cotovelo", "Joelho", "Calcanhar", "Dedão", "Pé", "Rabiosque", "Pança", "Papada", "Careca", "Borbulha", "Espinha", "Calo", "Arroto", "Soluço", "Espirro", "Ronco", "Peido", "Ressaca", "Vergonha alheia", "Mico", "Barraca", "Borrão", "Trapaceiro", "Totó", "Cabeça de vento", "Cromo", "Tótó", "Palerma", "Paspalho", "Crominho", "Morcão", "Nabo", "Batata", "Pato", "Pato Donald", "Shrek", "Bob Esponja", "Mr. Bean", "Gato das Botas", "Rato Mickey", "Homem-Aranha", "Hulk", "Thanos", "Gollum", "Dobby", "Harry Potter", "Darth Vader", "Yoda", "Willy Wonka", "Scooby-Doo" ]},
}

function getStoredCustomCategories() {
  try { return JSON.parse(localStorage.getItem("impostor_custom_categories") || "{}"); } catch { return {}; }
}
function getAllCategories() {
  const stored = getStoredCustomCategories();

  // Junta todas as categorias built-in
  const allWords = Object.values(BUILTIN_CATEGORIES)
    .flatMap(category => category.words);

  // Junta também as categorias personalizadas
  const customWords = Object.values(stored)
    .flatMap(category => category.words || []);

  // Remove palavras repetidas
  const uniqueWords = [...new Set([...allWords, ...customWords])];

  return {
    ...BUILTIN_CATEGORIES,
    ...stored,

    todas: {
      label: "Todas as Palavras",
      icon: "🌎",
      words: uniqueWords
    }
  };
}
